[2025-08-09T23:14:07.835+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-09T23:14:07.850+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data manual__2025-08-09T23:14:06.251842+00:00 [queued]>
[2025-08-09T23:14:07.855+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data manual__2025-08-09T23:14:06.251842+00:00 [queued]>
[2025-08-09T23:14:07.855+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-09T23:14:07.866+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-08-09 23:14:06.251842+00:00
[2025-08-09T23:14:07.870+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'manual__2025-08-09T23:14:06.251842+00:00', '--job-id', '864', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmp0zsrfz8z']
[2025-08-09T23:14:07.872+0000] {standard_task_runner.py:105} INFO - Job 864: Subtask generator_artist_data
[2025-08-09T23:14:07.872+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2495) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-09T23:14:07.872+0000] {standard_task_runner.py:72} INFO - Started process 2496 to run task
[2025-08-09T23:14:07.927+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data manual__2025-08-09T23:14:06.251842+00:00 [running]> on host f1a6d1411601
[2025-08-09T23:14:08.019+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T23:14:06.251842+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-09T23:14:06.251842+00:00'
[2025-08-09T23:14:08.020+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-09T23:14:08.430+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.11', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.11', 19092) IPv4]
[2025-08-09T23:14:08.435+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.11', 19092)]>: Broker version identified as 2.6
[2025-08-09T23:14:08.435+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.11', 19092)]>: Connection complete.
[2025-08-09T23:14:08.539+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [IPv4 ('172.18.0.8', 19092)]>: connecting to kafka-broker-2:19092 [('172.18.0.8', 19092) IPv4]
[2025-08-09T23:14:08.540+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connected> [IPv4 ('172.18.0.8', 19092)]>: Connection complete.
[2025-08-09T23:14:08.540+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.11', 19092)]>: Closing connection. 
[2025-08-09T23:14:08.554+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-09T23:14:08.657+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-09T23:14:08.762+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-09T23:14:08.866+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 59, in execute
    producer.send(self.kafka_topic, value=transaction)
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 845, in send
    value_bytes = self._serialize(
                  ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 978, in _serialize
    return f(data)
           ^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 54, in <lambda>
    value_serializer=lambda v: json.dumps(v).encode('utf-8'),
                               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-08-09T23:14:08.878+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=artist_generator, task_id=generator_artist_data, run_id=manual__2025-08-09T23:14:06.251842+00:00, execution_date=20250809T231406, start_date=20250809T231407, end_date=20250809T231408
[2025-08-09T23:14:08.892+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-09T23:14:08.893+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 864 for task generator_artist_data (Object of type date is not JSON serializable; 2496)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 59, in execute
    producer.send(self.kafka_topic, value=transaction)
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 845, in send
    value_bytes = self._serialize(
                  ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 978, in _serialize
    return f(data)
           ^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 54, in <lambda>
    value_serializer=lambda v: json.dumps(v).encode('utf-8'),
                               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-08-09T23:14:08.926+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-09T23:14:08.938+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-09T23:14:08.939+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
