[2025-08-05T21:28:25.742+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-05T21:28:25.749+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data manual__2025-08-05T21:28:24.246288+00:00 [queued]>
[2025-08-05T21:28:25.754+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data manual__2025-08-05T21:28:24.246288+00:00 [queued]>
[2025-08-05T21:28:25.754+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-05T21:28:25.760+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-08-05 21:28:24.246288+00:00
[2025-08-05T21:28:25.763+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'manual__2025-08-05T21:28:24.246288+00:00', '--job-id', '669', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmpxrwe57z3']
[2025-08-05T21:28:25.765+0000] {standard_task_runner.py:105} INFO - Job 669: Subtask generator_artist_data
[2025-08-05T21:28:25.763+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=256) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-05T21:28:25.765+0000] {standard_task_runner.py:72} INFO - Started process 258 to run task
[2025-08-05T21:28:25.787+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data manual__2025-08-05T21:28:24.246288+00:00 [running]> on host ef2c5d727bcb
[2025-08-05T21:28:25.816+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T21:28:24.246288+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T21:28:24.246288+00:00'
[2025-08-05T21:28:25.816+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-05T21:28:25.826+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.8', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.8', 19092) IPv4]
[2025-08-05T21:28:25.828+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.8', 19092)]>: Broker version identified as 2.6
[2025-08-05T21:28:25.828+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.8', 19092)]>: Connection complete.
[2025-08-05T21:28:25.829+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 58, in execute
    transaction = self.generate_artist_data(row_num)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 27, in generate_artist_data
    biography = fake.biography(nb_sentences=3)
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/faker/proxy.py", line 130, in __getattr__
    return getattr(self._factories[0], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Generator' object has no attribute 'biography'
[2025-08-05T21:28:25.835+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=artist_generator, task_id=generator_artist_data, run_id=manual__2025-08-05T21:28:24.246288+00:00, execution_date=20250805T212824, start_date=20250805T212825, end_date=20250805T212825
[2025-08-05T21:28:25.845+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-05T21:28:25.845+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 669 for task generator_artist_data ('Generator' object has no attribute 'biography'; 258)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 58, in execute
    transaction = self.generate_artist_data(row_num)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 27, in generate_artist_data
    biography = fake.biography(nb_sentences=3)
                ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/faker/proxy.py", line 130, in __getattr__
    return getattr(self._factories[0], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Generator' object has no attribute 'biography'
[2025-08-05T21:28:25.864+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-05T21:28:25.872+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-05T21:28:25.873+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
