[2025-08-04T21:50:31.875+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T21:50:31.900+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-07T00:00:00+00:00 [queued]>
[2025-08-04T21:50:31.910+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-07T00:00:00+00:00 [queued]>
[2025-08-04T21:50:31.910+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T21:50:31.922+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-01-07 00:00:00+00:00
[2025-08-04T21:50:31.929+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7192) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T21:50:31.930+0000] {standard_task_runner.py:72} INFO - Started process 7210 to run task
[2025-08-04T21:50:31.932+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'scheduled__2025-01-07T00:00:00+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmpzxyekzc6']
[2025-08-04T21:50:31.936+0000] {standard_task_runner.py:105} INFO - Job 235: Subtask generator_artist_data
[2025-08-04T21:50:32.016+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-07T00:00:00+00:00 [running]> on host c4e4284cebf8
[2025-08-04T21:50:32.125+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-07T00:00:00+00:00'
[2025-08-04T21:50:32.132+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T21:50:32.239+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:32.325+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 19092)]>: Broker version identified as 2.6
[2025-08-04T21:50:32.374+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:35.355+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:35.359+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:35.361+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:35.364+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:35.465+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:35.470+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:35.472+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. 
[2025-08-04T21:50:35.484+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName1', 'last_name': 'LastName1', 'dob': 'dob1', 'city': 'London', 'country': 'Germany'}
[2025-08-04T21:50:35.487+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName2', 'last_name': 'LastName2', 'dob': 'dob2', 'city': 'Delhi', 'country': 'South Africa'}
[2025-08-04T21:50:35.490+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName3', 'last_name': 'LastName3', 'dob': 'dob3', 'city': 'Vancouver', 'country': 'Canada'}
[2025-08-04T21:50:35.491+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName4', 'last_name': 'LastName4', 'dob': 'dob4', 'city': 'Berlin', 'country': 'Germany'}
[2025-08-04T21:50:35.487+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.493+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.492+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName5', 'last_name': 'LastName5', 'dob': 'dob5', 'city': 'Toronto', 'country': 'Germany'}
[2025-08-04T21:50:35.494+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.497+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName6', 'last_name': 'LastName6', 'dob': 'dob6', 'city': 'Manchester', 'country': 'Canada'}
[2025-08-04T21:50:35.498+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName7', 'last_name': 'LastName7', 'dob': 'dob7', 'city': 'Mumbai', 'country': 'Canada'}
[2025-08-04T21:50:35.498+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName8', 'last_name': 'LastName8', 'dob': 'dob8', 'city': 'London', 'country': 'India'}
[2025-08-04T21:50:35.497+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.499+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName9', 'last_name': 'LastName9', 'dob': 'dob9', 'city': 'Edinburgh', 'country': 'India'}
[2025-08-04T21:50:35.500+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName10', 'last_name': 'LastName10', 'dob': 'dob10', 'city': 'Berlin', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.502+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName11', 'last_name': 'LastName11', 'dob': 'dob11', 'city': 'Durban', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.503+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName12', 'last_name': 'LastName12', 'dob': 'dob12', 'city': 'Montreal', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.504+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName13', 'last_name': 'LastName13', 'dob': 'dob13', 'city': 'Delhi', 'country': 'India'}
[2025-08-04T21:50:35.505+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName14', 'last_name': 'LastName14', 'dob': 'dob14', 'city': 'Durban', 'country': 'Germany'}
[2025-08-04T21:50:35.505+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName15', 'last_name': 'LastName15', 'dob': 'dob15', 'city': 'Cape Town', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.507+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName16', 'last_name': 'LastName16', 'dob': 'dob16', 'city': 'Durban', 'country': 'Germany'}
[2025-08-04T21:50:35.508+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName17', 'last_name': 'LastName17', 'dob': 'dob17', 'city': 'Delhi', 'country': 'Canada'}
[2025-08-04T21:50:35.509+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName18', 'last_name': 'LastName18', 'dob': 'dob18', 'city': 'Cape Town', 'country': 'South Africa'}
[2025-08-04T21:50:35.509+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName19', 'last_name': 'LastName19', 'dob': 'dob19', 'city': 'Bangalore', 'country': 'Germany'}
[2025-08-04T21:50:35.510+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName20', 'last_name': 'LastName20', 'dob': 'dob20', 'city': 'Delhi', 'country': 'South Africa'}
[2025-08-04T21:50:35.529+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.531+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.531+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.532+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.633+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.635+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.635+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.636+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.845+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:38.269+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
[2025-08-04T21:50:38.282+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:52:35.482+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 20 record(s) for TopicPartition(topic='artist_data', partition=0): 120000 ms has passed since batch creation
[2025-08-04T21:52:35.485+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 20 record(s) for TopicPartition(topic='artist_data', partition=0): 120000 ms has passed since batch creation
[2025-08-04T21:52:35.485+0000] {artist_kafka_operator.py:51} INFO - 20 transactions sent has been sent to kafka artist_data!
[2025-08-04T21:52:35.487+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. 
[2025-08-04T21:52:35.508+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T21:52:35.510+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=artist_generator, task_id=generator_artist_data, run_id=scheduled__2025-01-07T00:00:00+00:00, execution_date=20250107T000000, start_date=20250804T215031, end_date=20250804T215235
[2025-08-04T21:52:35.576+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-04T21:52:35.600+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T21:52:35.600+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
