[2025-08-03T23:21:32.829+0000] {processor.py:186} INFO - Started process (PID=3814) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:21:32.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:21:32.831+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:21:32.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:21:32.837+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:21:32.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:21:32.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:21:32.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.035 seconds
[2025-08-03T23:22:03.149+0000] {processor.py:186} INFO - Started process (PID=3835) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:22:03.150+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:22:03.151+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:22:03.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:22:03.155+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:22:03.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:22:03.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:22:03.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.035 seconds
[2025-08-03T23:22:33.469+0000] {processor.py:186} INFO - Started process (PID=3859) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:22:33.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:22:33.472+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:22:33.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:22:33.478+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:22:33.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:22:33.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:22:33.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.039 seconds
[2025-08-03T23:23:03.933+0000] {processor.py:186} INFO - Started process (PID=3884) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:23:03.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:23:03.936+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:23:03.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:23:03.941+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:23:03.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:23:03.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:23:03.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.032 seconds
[2025-08-03T23:23:34.419+0000] {processor.py:186} INFO - Started process (PID=3911) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:23:34.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:23:34.421+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:23:34.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:23:34.424+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:23:34.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:23:34.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:23:34.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.022 seconds
[2025-08-03T23:24:04.899+0000] {processor.py:186} INFO - Started process (PID=3936) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:24:04.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:24:04.902+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:24:04.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:24:04.907+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:24:04.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:24:04.908+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:24:04.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.054 seconds
[2025-08-03T23:24:35.525+0000] {processor.py:186} INFO - Started process (PID=3962) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:24:35.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:24:35.530+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:24:35.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:24:35.537+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:24:35.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:24:35.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:24:35.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.046 seconds
[2025-08-03T23:25:05.882+0000] {processor.py:186} INFO - Started process (PID=3986) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:25:05.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:25:05.884+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:25:05.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:25:05.888+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:25:05.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:25:05.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:25:05.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.029 seconds
[2025-08-03T23:25:36.214+0000] {processor.py:186} INFO - Started process (PID=4012) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:25:36.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:25:36.221+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:25:36.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:25:36.227+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:25:36.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:25:36.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:25:36.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.039 seconds
[2025-08-03T23:26:06.553+0000] {processor.py:186} INFO - Started process (PID=4038) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:26:06.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:26:06.555+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:26:06.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:26:06.559+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:26:06.557+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:26:06.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:26:06.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.025 seconds
[2025-08-03T23:26:37.137+0000] {processor.py:186} INFO - Started process (PID=4069) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:26:37.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:26:37.139+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:26:37.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:26:37.143+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:26:37.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:26:37.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:26:37.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.027 seconds
[2025-08-03T23:27:07.483+0000] {processor.py:186} INFO - Started process (PID=4095) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:27:07.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:27:07.485+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:27:07.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:27:07.488+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:27:07.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:27:07.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:27:07.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.027 seconds
[2025-08-03T23:27:38.064+0000] {processor.py:186} INFO - Started process (PID=4121) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:27:38.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:27:38.066+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:27:38.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:27:38.071+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:27:38.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:27:38.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:27:38.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.029 seconds
[2025-08-03T23:28:08.656+0000] {processor.py:186} INFO - Started process (PID=4147) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:28:08.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:28:08.658+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:28:08.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:28:08.663+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:28:08.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:28:08.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:28:08.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.038 seconds
[2025-08-03T23:28:39.229+0000] {processor.py:186} INFO - Started process (PID=4173) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:28:39.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:28:39.232+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:28:39.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:28:39.239+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:28:39.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:28:39.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:28:39.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.043 seconds
[2025-08-03T23:29:10.201+0000] {processor.py:186} INFO - Started process (PID=4199) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:29:10.202+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:29:10.203+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:29:10.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:29:10.207+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:29:10.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:29:10.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:29:10.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.039 seconds
[2025-08-03T23:29:40.565+0000] {processor.py:186} INFO - Started process (PID=4225) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:29:40.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:29:40.567+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:29:40.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:29:40.574+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:29:40.571+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:29:40.574+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:29:40.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.040 seconds
[2025-08-03T23:30:11.727+0000] {processor.py:186} INFO - Started process (PID=4251) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:30:11.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:30:11.742+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:30:11.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:30:11.776+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:30:11.766+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:30:11.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:30:12.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.375 seconds
[2025-08-03T23:30:42.525+0000] {processor.py:186} INFO - Started process (PID=4277) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:30:42.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:30:42.527+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:30:42.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:30:42.533+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:30:42.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:30:42.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:30:42.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.047 seconds
[2025-08-03T23:31:13.194+0000] {processor.py:186} INFO - Started process (PID=4303) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:31:13.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:31:13.197+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:31:13.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:31:13.202+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:31:13.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:31:13.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:31:13.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.061 seconds
[2025-08-03T23:31:43.889+0000] {processor.py:186} INFO - Started process (PID=4329) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:31:43.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:31:43.890+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:31:43.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:31:43.893+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:31:43.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:31:43.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:31:43.915+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.036 seconds
[2025-08-03T23:32:14.425+0000] {processor.py:186} INFO - Started process (PID=4355) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:32:14.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:32:14.429+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:32:14.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:32:14.439+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:32:14.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:32:14.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:32:14.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.044 seconds
[2025-08-03T23:32:44.993+0000] {processor.py:186} INFO - Started process (PID=4381) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:32:44.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:32:44.995+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:32:44.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:32:44.999+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:32:44.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:32:44.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:32:45.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.037 seconds
[2025-08-03T23:33:15.610+0000] {processor.py:186} INFO - Started process (PID=4407) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:33:15.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:33:15.615+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:33:15.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:33:15.626+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:33:15.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:33:15.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:33:15.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.048 seconds
[2025-08-03T23:33:46.148+0000] {processor.py:186} INFO - Started process (PID=4439) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:33:46.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:33:46.151+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:33:46.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:33:46.155+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:33:46.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:33:46.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:33:46.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.041 seconds
[2025-08-03T23:34:16.783+0000] {processor.py:186} INFO - Started process (PID=4465) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:34:16.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:34:16.787+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:34:16.786+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:34:16.791+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:34:16.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:34:16.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:34:16.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.041 seconds
[2025-08-03T23:34:47.487+0000] {processor.py:186} INFO - Started process (PID=4496) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:34:47.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:34:47.491+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:34:47.490+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:34:47.498+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:34:47.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:34:47.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:34:47.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.035 seconds
[2025-08-03T23:35:17.859+0000] {processor.py:186} INFO - Started process (PID=4522) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:35:17.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:35:17.861+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:35:17.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:35:17.864+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:35:17.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:35:17.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:35:17.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.038 seconds
[2025-08-03T23:35:48.306+0000] {processor.py:186} INFO - Started process (PID=4548) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:35:48.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:35:48.308+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:35:48.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:35:48.312+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:35:48.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:35:48.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:35:48.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.024 seconds
[2025-08-03T23:36:18.578+0000] {processor.py:186} INFO - Started process (PID=4574) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:36:18.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:36:18.580+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:36:18.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:36:18.584+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:36:18.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:36:18.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:36:18.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.028 seconds
[2025-08-03T23:36:48.891+0000] {processor.py:186} INFO - Started process (PID=4600) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:36:48.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:36:48.893+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:36:48.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:36:48.896+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:36:48.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:36:48.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:36:48.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.027 seconds
[2025-08-03T23:37:19.230+0000] {processor.py:186} INFO - Started process (PID=4626) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:37:19.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:37:19.233+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:37:19.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:37:19.237+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:37:19.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:37:19.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:37:19.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.037 seconds
[2025-08-03T23:37:49.696+0000] {processor.py:186} INFO - Started process (PID=4652) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:37:49.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:37:49.697+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:37:49.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:37:49.701+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:37:49.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:37:49.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:37:49.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.025 seconds
[2025-08-03T23:38:19.993+0000] {processor.py:186} INFO - Started process (PID=4678) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:38:19.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:38:19.996+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:38:19.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:38:19.999+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:38:19.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:38:20.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:38:20.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.032 seconds
[2025-08-03T23:38:50.508+0000] {processor.py:186} INFO - Started process (PID=4704) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:38:50.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:38:50.511+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:38:50.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:38:50.515+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:38:50.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:38:50.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:38:50.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.045 seconds
[2025-08-03T23:39:20.855+0000] {processor.py:186} INFO - Started process (PID=4730) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:39:20.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:39:20.857+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:39:20.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:39:20.860+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:39:20.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:39:20.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:39:20.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.028 seconds
[2025-08-03T23:39:51.311+0000] {processor.py:186} INFO - Started process (PID=4756) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:39:51.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:39:51.313+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:39:51.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:39:51.317+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:39:51.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:39:51.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:39:51.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.027 seconds
[2025-08-03T23:40:21.610+0000] {processor.py:186} INFO - Started process (PID=4782) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:40:21.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:40:21.612+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:40:21.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:40:21.615+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:40:21.614+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:40:21.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:40:21.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.024 seconds
[2025-08-03T23:40:52.183+0000] {processor.py:186} INFO - Started process (PID=4808) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:40:52.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:40:52.185+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:40:52.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:40:52.190+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:40:52.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:40:52.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:40:52.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.035 seconds
[2025-08-03T23:41:22.672+0000] {processor.py:186} INFO - Started process (PID=4834) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:41:22.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:41:22.674+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:41:22.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:41:22.677+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:41:22.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:41:22.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:41:22.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.026 seconds
[2025-08-03T23:41:53.220+0000] {processor.py:186} INFO - Started process (PID=4860) to work on /opt/airflow/dags/streams_generator.py
[2025-08-03T23:41:53.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/streams_generator.py for tasks to queue
[2025-08-03T23:41:53.223+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:41:53.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:41:53.227+0000] {logging_mixin.py:190} INFO - [2025-08-03T23:41:53.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/streams_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/streams_generator.py", line 3
    from
        ^
SyntaxError: invalid syntax
[2025-08-03T23:41:53.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/streams_generator.py
[2025-08-03T23:41:53.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/streams_generator.py took 0.033 seconds
